/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import database.Database;
import database.detail_transaksi;
import database.detail_transaksiTableModel;
import database.transaksi;
import javax.swing.JOptionPane;
import main.sessionTransaksi;

/**
 *
 * @author bandi
 */
public class detail_transaksiViews extends javax.swing.JInternalFrame {

    private static detail_transaksiViews myInstance;

    public static detail_transaksiViews getInstance() {
        if (myInstance == null) {
            myInstance = new detail_transaksiViews();
        }
        return myInstance;
    }
    
    public String id_detail_transaksi;
    /**
     * Creates new form penggunaViews
     */
    public detail_transaksiViews() {
        initComponents();
        id_detail_transaksi = sessionTransaksi.getTampil_id_transaksi();
        txtId_transaksi.setText(id_detail_transaksi);
        tampilData();
    }
    
    public void tampilData(){
        Database db = new Database();
        detail_transaksiTableModel tabeldetailtransaksi = new detail_transaksiTableModel();
        tabeldetailtransaksi.setData(db.tampil_semua_detail_transaksi(id_detail_transaksi));
        tblDetail_transaksi.setModel(tabeldetailtransaksi);
        txtId.setText("");
        txt_Id_menu.setText("");
        txtJumlah_Beli.setText("");
        txtTotal_harga.setText("");
    }

    public void refreshdata(){
        Database db = new Database();
        detail_transaksiTableModel tabeldetailtransaksi = new detail_transaksiTableModel();
        tabeldetailtransaksi.setData(db.tampil_semua_detail_transaksi(id_detail_transaksi));
        tabeldetailtransaksi.fireTableDataChanged();
        tblDetail_transaksi.changeSelection(0, 0, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId_transaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail_transaksi = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_Id_menu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJumlah_Beli = new javax.swing.JTextField();
        txtTotal_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setTitle("Detail Transaksi");

        jLabel1.setText("Data Detail Transaksi");

        txtId_transaksi.setEditable(false);
        txtId_transaksi.setText("0");

        jLabel4.setText("ID");

        txtId.setEditable(false);
        txtId.setText("0");

        tblDetail_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Transaksi", "ID Menu", "Jumlah Beli", "Total Harga"
            }
        ));
        tblDetail_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetail_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetail_transaksi);

        jLabel8.setText("ID Transaksi");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Menu");

        jLabel3.setText("Jumlah Beli");

        jLabel5.setText("Total Harga");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Id_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah_Beli, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnKembali))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Id_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJumlah_Beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnCari)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.tambah_detail_transaksi(new detail_transaksi(
                txtId.getText(),
                txtId_transaksi.getText(),
                txt_Id_menu.getText(),
                Integer.parseInt(txtJumlah_Beli.getText()),
                Integer.parseInt(txtTotal_harga.getText())
        ));
        tampilData();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword;
        keyword = JOptionPane.showInputDialog(null,"Masukan id menu yang dicari : ",
                "Filter/Pencarian",JOptionPane.QUESTION_MESSAGE);
        if(keyword!=null){
             Database db = new Database();
            detail_transaksiTableModel tabeldetailtransaksi = new detail_transaksiTableModel();
            tabeldetailtransaksi.setData(db.filter_detail_transaksi(keyword,id_detail_transaksi));
            tblDetail_transaksi.setModel(tabeldetailtransaksi);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblDetail_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetail_transaksiMouseClicked
        // TODO add your handling code here:
        Database db = new Database();
        detail_transaksiTableModel tabeldetailtransaksi = new detail_transaksiTableModel();
        tabeldetailtransaksi.setData(db.tampil_semua_detail_transaksi(id_detail_transaksi));
        
        int baris = tblDetail_transaksi.getSelectedRow();
        String id = (String)tblDetail_transaksi.getValueAt(baris, 0);
        String id_transaksi = (String)tblDetail_transaksi.getValueAt(baris, 1);
        String id_menu = (String)tblDetail_transaksi.getValueAt(baris, 2);
        int jumlah_beli = (int)tblDetail_transaksi.getValueAt(baris, 3);
        int total_harga = (int)tblDetail_transaksi.getValueAt(baris, 4);
        detail_transaksi dt = db.pilih_detail_transaksi(id);
        
        if(dt!=null){
            txtId.setText(id);
            txtId_transaksi.setText(id_transaksi);
            txt_Id_menu.setText(id_menu);
            txtJumlah_Beli.setText(String.valueOf(jumlah_beli));
            txtTotal_harga.setText(String.valueOf(total_harga));
        } else {
            JOptionPane.showMessageDialog(null, "Detail transaksi dengan ID "+id+" tidak ditemukan!");
        }
    }//GEN-LAST:event_tblDetail_transaksiMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblDetail_transaksi;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId_transaksi;
    private javax.swing.JTextField txtJumlah_Beli;
    private javax.swing.JTextField txtTotal_harga;
    private javax.swing.JTextField txt_Id_menu;
    // End of variables declaration//GEN-END:variables
}
