/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import database.Database;
import database.transaksi;
import database.transaksiTableModel;
import frames.mainFrame;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import main.sessionAlur;
import main.sessionPengguna;
import main.sessionTransaksi;


/**
 *
 * @author bandi
 */
public class transaksiViews extends javax.swing.JInternalFrame {
    
    private static transaksiViews myInstance;

    public static transaksiViews getInstance() {
        if (myInstance == null) {
            myInstance = new transaksiViews();
        }
        return myInstance;
    }
    
    /**
     * Creates new form penggunaViews
     */
       
    public transaksiViews() {
        initComponents();
        tampilData();
    }

    public void tampilData(){
        Database db = new Database();
        transaksiTableModel tabeltransaksi = new transaksiTableModel();
        tabeltransaksi.setData(db.tampil_semua_transaksi());
        tblTransaksi.setModel(tabeltransaksi);
    }

    public void refreshdata(){
        Database db = new Database();
        transaksiTableModel tabeltransaksi = new transaksiTableModel();
        tabeltransaksi.setData(db.tampil_semua_transaksi());
        tabeltransaksi.fireTableDataChanged();
        tblTransaksi.changeSelection(0, 0, false, false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTampilkan = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblId_selected = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setTitle("Transaksi");

        jLabel1.setText("Data Transaksi");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Total Harga", "Bayar", "Kembalian", "Kasir"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Transaksi Selected:");

        lblId_selected.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnTampilkan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblId_selected, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblId_selected))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnTampilkan)
                    .addComponent(btnCari)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        String id_totransaksi = lblId_selected.getText();
        sessionTransaksi.setTampil_id_transaksi(id_totransaksi);
        detail_transaksiViews detailtransaksi = detail_transaksiViews.getInstance();
        detailtransaksi.pack();
        if (detailtransaksi.isVisible()) {
        } else {
            getDesktopPane().add(detailtransaksi);
            detailtransaksi.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        String alur_id_transaksi = db.tambah_alur_persiapan_transaksi();
        sessionAlur.setAlur_id_transaksi(alur_id_transaksi);
        tambahAlurDetailTransaksiViews tambahalurdetailtransaksi = tambahAlurDetailTransaksiViews.getInstance();
        tambahalurdetailtransaksi.pack();
        if (tambahalurdetailtransaksi.isVisible()) {
        } else {
            getDesktopPane().add(tambahalurdetailtransaksi);
            tambahalurdetailtransaksi.setVisible(true);
            this.dispose();
        }
        /*try {
            tambahalurdetailtransaksi.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        Database db = new Database();
        transaksiTableModel tabeltransaksi = new transaksiTableModel();
        tabeltransaksi.setData(db.tampil_semua_transaksi());
        
        int baris = tblTransaksi.getSelectedRow();
        String id = (String)tblTransaksi.getValueAt(baris, 0);
        String tanggal = (String)tblTransaksi.getValueAt(baris, 1);
        int total_harga = (int)tblTransaksi.getValueAt(baris, 2);
        int bayar = (int)tblTransaksi.getValueAt(baris, 3);
        int kembalian = (int)tblTransaksi.getValueAt(baris, 4);
        String kasir = (String)tblTransaksi.getValueAt(baris, 5);
        transaksi t = db.pilih_transaksi(id);
        
        if(t!=null){
            lblId_selected.setText(id);
        } else {
            JOptionPane.showMessageDialog(null, "ID Transaksi dengan ID "+id+" tidak ditemukan!");
        }
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword;
        keyword = JOptionPane.showInputDialog(null,"Masukan tanggal transaksi yang dicari : ",
                "Filter/Pencarian",JOptionPane.QUESTION_MESSAGE);
        if(keyword!=null){
            Database db = new Database();
            transaksiTableModel tabeltransaksi = new transaksiTableModel();
            tabeltransaksi.setData(db.filter_transaksi(keyword));
            tblTransaksi.setModel(tabeltransaksi);
        }
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblId_selected;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables
}
